import Head from "next/head";
import { request } from "../lib/datocms";
// token = d002a11e3deb2c286417fce33fa2b7
const HOMEPAGE_QUERY = `
query HomePage($limit: IntType){
  allProducts(first: $limit){
    createdAt
    id
    slug
    bought
    _status
    name
    price
    description
    image {
      id
      width
      height
      size
      alt
    }
  }
}`;

export async function getStaticProps() {
  const data = await request({
    query: HOMEPAGE_QUERY,
    variables: { limit: 10 },
  });
  return {
    props: { data }, // will be passed to the page component as props
  };
}

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {console.log(data)}
    </div>
  );
}
